### ISSUE TITLE
How to install when pip isn't available?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [caronc/nzbget-tidyit#10]
Hi

So I'm no computer guru, but I'm trying to install this in a NZBGet container that doesn't have pip installed: 

https://hub.docker.com/r/linuxserver/nzbget/

I copied the .py file to my scripts folder and restarted nzbget; now the item does show up in the list, but according to the install instructions I also NEED to run `pip install -r requirements.txt` and w/out pip installed how can I do this?

Any help appreciated! :)

**Comment by caronc** [comment]
Did you get this figured out? Sorry for the delayed response
