### ISSUE TITLE
No Module "six"

### ISSUE THREAD

**Issue by pb1051** [caronc/nzbget-tidyit#11]
:beetle: **Describe the bug**
Trying to get this script to work on a containerized install of PG Blitz. NZBget can see the script but I get the error below. I've tried updating the pip and python, but to no avail.

:bulb: **Screenshots and Logs**
```
Executing script TidyIt.py with command DoTidy
Traceback (most recent call last):
File "/config/scripts/TidyIt.py", line 279, in <module>
from nzbget import SKIP_DIRECTORIES
File "/usr/lib/python3.8/site-packages/nzbget/__init__.py", line 23, in <module>
from .ScriptBase import *
File "/usr/lib/python3.8/site-packages/nzbget/ScriptBase.py", line 135, in <module>
import six
ModuleNotFoundError: No module named 'six'
Script TidyIt.py with command DoTidy failed (terminated with unknown status)
```

:computer: **Your System Details:**
 - OS: Linux Debian-99-stretch-64-minimal 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
 - Python Version: Python 2.7.13

:crystal_ball: **Additional context**

**Comment by caronc** [comment]
You just need to haul in the requirements that go with TidyIt ([see here](https://github.com/caronc/nzbget-tidyit#installation-instructions))
`pip install -r requirements.txt`

**Comment by pb1051** [comment]
I ran this command in the / directory, but that didn't solve it

**Comment by caronc** [comment]
There is definitely something strange going on with your environment. You could just try installing the missing dependency:

```bash
pip install six
```

**Comment by pb1051** [comment]
So here's the output from the install command:

> pip install six
> 
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> 
> Defaulting to user installation because normal site-packages is not writeable
> 
> Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (1.15.0)

I wonder what's up with my environment.

**Comment by caronc** [comment]
Probably try the same command again but with sudo in front:
```bash
sudo pip install six
```

If the package appear damaged, you might be able to reset your environment with:
```bash
sudo pip uninstall pynzbget six
# Then reinstall:
sudo pip install pynzbget
```

**Comment by pb1051** [comment]
I dunno. I did it as sudo and then completed the commands you pasted and after reboot it did not solve the issue. I guess I'll abandon my attempts.

**Comment by caronc** [comment]
Did your error message change at all; or do you still get the same one?

**Comment by pb1051** [comment]
It's the same error...

**Comment by caronc** [comment]
Make sure you're running the following commands inside your container (not in your native working environment):
```bash
sudo pip uninstall pynzbget six
# Then reinstall:
sudo pip install pynzbget
```

After re-reading what you explained and what i suggested, i may have created disconnect as to where you need to run these commands.

Can you share with me the `docker-compose.yml` file or `Dockerfile` you're using?  Maybe i can help out fixing your issue there?

**Comment by pb1051** [comment]
You can close this for now. I've switched from PG Blitz to CloudBox implementation and don't need this at the moment.
